name: "Elegoo HA"
version: "1.0.0"
slug: elegoo-ha
description: >-
  "Integrate your Elegoo 3D printer with Home Assistant."
arch:
  - amd64
url: "https://github.com/danielcherubini/elegoo-homeassistant"
# ports:
#   123/tcp: 123
options:
  printer_ip: ""
schema:
  printer_ip: str
# map:
#   - type: share
#     read_only: False
#   - type: ssl
#   - type: homeassistant_config
#     read_only: False
#     path: /custom/config/path
